### ISSUE TITLE
prereleases/alphas: Settle on a naming scheme for commits that do not have tags

### ISSUE THREAD

**Issue by reiner-dolp** [liblouis/js-build#1]
- [ ] Package managers require semantic versioning. ~Liblouis does not use semantic versioning. Add a warning that users should only require a specific tags and not version ranges to avoid programs breaking.~ Add a warning that version ranges should only be used if no personal tables (only tables bundled with the release) are used.
- [ ] Settle on a naming scheme, that generates the correct order in semantic versioning for builds that do not have a tag in the liblouis/liblouis-repository. Possible formats:
     - **`[liblouis version]-[fixed string]+[commit hash]`**:
        Example for the current repository HEAD: `3.2.0-prerelease+d32300c` or `3.2.0-nightly+d32300c` or    `3.2.0-alpha+d32300c`. All prereleases are considered identical by the package manager as everything after `+` is dropped before version comparision.
     - **`[liblouis version](-[fixed string]).[increment](+[commit hash])`**:
        Example `3.2.0-1` is the first commit after release `3.1.0` or `3.2.0-alpha.1` or `3.2.0-alpha.1+d32300c`. These are correctly ordered.
     - **`0.0.0+[commit hash]`**:
        Incorrect order, but easy to implement. Probably covers most use cases.

**Comment by bertfrees** [comment]
I like the second option but I'm not sure how to compute the `[increment]`. How to determine which commits have been built by Travis previously? Another thing to note is that is it not always known from the start what the next version will be. E.g. in theory it could be either `3.1.1`, `3.2.0` or even `4.0.0`.

**Comment by reiner-dolp** [comment]
We could compute `increment` as the number of commits since the last tag:
```
git rev-list v3.1.0..HEAD --count
```
This should work if we restrict builds to the master branch as planned. (multiple branches could cause collisions.)

Not knowing the version number of the next release is indeed an issue I haven't thought of. How do you decide what the next version number is?

**Comment by bertfrees** [comment]
Travis does not build every single commit, so this would mean certain versions numbers are skipped. Is that OK?

**Comment by reiner-dolp** [comment]
Skipping increments is not an issue at all.

**Comment by egli** [comment]
Just trying to understand the problem here.

1. I thought we were using semantic versioning for liblouis. Are we not? Is there something we can do to improve this on the liblouis side?
2. For labeling can't you just use something along the lines of `git describe`?

**Comment by reiner-dolp** [comment]
NPM allows you fetch/install specific versions of a repository/package using versions, tags or commit hashes. Installing official releases or the most recent commit already works and has a nice syntax:

```yml
# most recent official release in the main repository
npm install liblouis-build@latest
# or simply
npm install liblouis-build
```
```yml
# build of the most recent commit to the main repository
npm install liblouis-build@next
```
```yml
# use a specific official release
npm install liblouis-build@3.1.0
# or with an alternative syntax
npm install liblouis/js-build#v3.1.0
```

We are trying to find a naming scheme that lets you install a build of a specific commit to the main repository, e.g. commit ff425bc in the liblouis/liblouis repository. Usually that is not an issue, because
you can simply install a specific commit using
```yml
npm install liblouis/js-build#ff425bc
```
However, this does not work, as this is referencing commit shas in *liblouis/js-build* and not *liblouis/liblouis*. We are trying to find a naming scheme that lets you get a build only given a commit sha in the main repository, while still generating a meaningful order according to the schemantic versioning spec.

**Comment by reiner-dolp** [comment]
I've been thinking about this yesterday. It would probably make sense to just release commits that are not tagged in the main repo as `v0.0.0+[main repo commit hash]`. The only usecase I can think of, where a per commit correctly ordered release list is practical, is the test-drive website I wrote. In all other scenarios, you probably want the latest commit, the latest release, or a specific commit. Releasing arbitrary incompatible versions as release `0.x.x` does not violate the semver spec.

**Comment by reiner-dolp** [comment]
Thanks Christian. I was not aware of `git describe`. It would require some string substitutions as `-` , `+` and `.` are interpreted by NPM.
